# Generated by Django 3.2.25 on 2024-07-25 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20240725_0943'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductReview',
        ),
    ]
